### Calculate price for German customer with coupon
POST http://test.local/calculate-price
Content-Type: application/json

{
    "product": 1,
    "taxNumber": "DE123456789",
    "couponCode": "D15"
}

### Calculate price for Italian customer without coupon
POST http://test.local/calculate-price
Content-Type: application/json

{
    "product": 1,
    "taxNumber": "IT12345678900"
}

### Calculate price for Greek customer with percentage coupon
POST http://test.local/calculate-price
Content-Type: application/json

{
    "product": 1,
    "taxNumber": "GR123456789",
    "couponCode": "P10"
}

### Purchase with PayPal
POST http://test.local/purchase
Content-Type: application/json

{
    "product": 1,
    "taxNumber": "IT12345678900",
    "couponCode": "D15",
    "paymentProcessor": "paypal"
}

### Purchase with Stripe
POST http://test.local/purchase
Content-Type: application/json

{
    "product": 2,
    "taxNumber": "FRAA123456789",
    "couponCode": "P10",
    "paymentProcessor": "stripe"
}

### Invalid request - missing product
POST http://test.local/calculate-price
Content-Type: application/json

{
    "taxNumber": "DE123456789"
}

### Invalid request - wrong tax number
POST http://test.local/calculate-price
Content-Type: application/json

{
    "product": 1,
    "taxNumber": "US123456789",
    "couponCode": "D15"
}

### Not found product
POST http://test.local/calculate-price
Content-Type: application/json

{
    "product": 111,
    "taxNumber": "DE123456789",
    "couponCode": "D15"
}
